#!/bin/bash
# Setup script for Mochi Scripts - configures environment variables
# Run this after cloning the repo to set up your local config

echo "🐱 Setting up Mochi Scripts environment..."

# Determine config location
if [ -d "/root/.openclaw" ]; then
    # Running on OpenClaw/KiloClaw server
    CONFIG_DIR="/root/.openclaw/workspace"
elif [ -d "$HOME/.openclaw" ]; then
    # Running on local machine
    CONFIG_DIR="$HOME/.openclaw/workspace"
else
    # Fallback
    CONFIG_DIR="$HOME"
fi

CONFIG_FILE="$CONFIG_DIR/.env"

# Check if .env already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Config file already exists at $CONFIG_FILE"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Create .env with user input
echo "📝 Creating .env file at $CONFIG_FILE"
echo "# Mochi Scripts Configuration" > "$CONFIG_FILE"
echo "# Generated by setup.sh on $(date)" >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

# Ask for LEAH_EMAIL
echo -n "Enter Leah's Gmail address [lia.the.adventurer@gmail.com]: "
read -r input_email
LEAH_EMAIL="${input_email:-lia.the.adventurer@gmail.com}"
echo "LEAH_EMAIL=$LEAH_EMAIL" >> "$CONFIG_FILE"
echo "" >> "$CONFIG_FILE"

# Also create .env in scripts directory for runtime
echo "LEAH_EMAIL=$LEAH_EMAIL" > /root/.openclaw/scripts/.env
chmod 600 /root/.openclaw/scripts/.env
echo "✅ Also configured /root/.openclaw/scripts/.env for runtime"
echo ""

# Ask for TIRI_EMAIL
echo -n "Enter Tiri's AgentMail address [tiramisu@agentmail.to]: "
read -r input_tiri
TIRI_EMAIL="${input_tiri:-tiramisu@agentmail.to}"
echo "TIRI_EMAIL=$TIRI_EMAIL" >> "$CONFIG_FILE"
# Also append to scripts/.env
echo "TIRI_EMAIL=$TIRI_EMAIL" >> /root/.openclaw/scripts/.env
echo "" >> "$CONFIG_FILE"

# Optional: Moltbook token
echo -n "Enter Moltbook API token (optional, press Enter to skip): "
read -r input_moltbook
if [ -n "$input_moltbook" ]; then
    echo "MOLTBOOK_TOKEN=$input_moltbook" >> "$CONFIG_FILE"
fi

echo "" >> "$CONFIG_FILE"
echo "# Google OAuth credentials are stored in .gog_refresh_token.json" >> "$CONFIG_FILE"
echo "# (already configured via gog CLI)" >> "$CONFIG_FILE"

# Set permissions
chmod 600 "$CONFIG_FILE"

echo "✅ Configuration saved to $CONFIG_FILE"
echo ""
echo "📋 Next steps:"
echo "1. Ensure your cron jobs/scripts source this file, or:"
echo "   source $CONFIG_FILE"
echo ""
echo "2. Test a script:"
echo "   source $CONFIG_FILE && ./check-gmail-shipments.sh"
echo ""
echo "Or add to your shell profile (~/.bashrc, ~/.zshrc):"
echo "  source $CONFIG_FILE"
echo ""
